// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRxq8ziH2gLY6aNFcjnLwhFk3XhYvdvs',
    appId: '1:244628934638:web:1d63fffcae5ab153df08ff',
    messagingSenderId: '244628934638',
    projectId: 'parcelhub-siswa',
    authDomain: 'parcelhub-siswa.firebaseapp.com',
    databaseURL: 'https://parcelhub-siswa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parcelhub-siswa.firebasestorage.app',
    measurementId: 'G-46EW7X3FTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdLhNgRBEQmFx589XcsVvmJAoyFhdJYs',
    appId: '1:244628934638:android:9fa34c2293d3061adf08ff',
    messagingSenderId: '244628934638',
    projectId: 'parcelhub-siswa',
    databaseURL: 'https://parcelhub-siswa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parcelhub-siswa.firebasestorage.app',
  );

}